version: '3'

services:
  paperless-ngx:
    image: lscr.io/linuxserver/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - PAPERLESS_URL=https://papers.mydomain.com
    volumes:
      - /home/fmrh/paperless-ngx/config:/config
      - /home/fmrh/paperless-ngx/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless-ngx-secure.entrypoints=https"
      - "traefik.http.routers.paperless-ngx-secure.rule=Host(`papers.mydomain.com`)"
      - "traefik.http.routers.paperless-ngx-secure.tls=true"
      - "traefik.http.routers.paperless-ngx-secure.service=paperless-ngx"
      - "traefik.http.services.paperless-ngx.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
